### ISSUE TITLE
'Failed to create CoreCLR' after upgrade to radar-3.1.0.4690-1.el8

### ISSUE THREAD

**Issue by tim427** [negativo17/radarr#1]
Since version 'radar-3.1.0.4690-1.el8' the service isn't able to start with the following error "Failed to create CoreCLR, HRESULT: 0x80004005"

Rollback to 'radarr-3.1.0.4624-1.el8.x86_64' works without an issue!

Also manual starting, works without an issue; `sudo -u radarr /usr/lib64/radarr/Radarr -nobrowser -data /var/lib/radarr`

Log entries;
```
Mar 12 12:02:08 downloadmachine systemd[1]: Started Automated manager and downloader for Movies.
-- Subject: Unit radarr.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit radarr.service has finished starting up.
--
-- The start-up result is done.
Mar 12 12:02:08 downloadmachine Radarr[4833]: Failed to create CoreCLR, HRESULT: 0x80004005
Mar 12 12:02:08 downloadmachine systemd[1]: radarr.service: Main process exited, code=exited, status=137/n/a
Mar 12 12:02:08 downloadmachine systemd[1]: radarr.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- The unit radarr.service has entered the 'failed' state with result 'exit-code'.
```

PS; Same happend with https://github.com/negativo17/lidarr/

**Comment by scaronni** [comment]
Hi, yes, unfortunately the latest builds of Radarr are now a .NET static binary, and the SELinux policies are missing.

Short term workaround, you can set SELinux in permissive mode (`setenforce 0`) or generate the necessary SELinux custom polcies:
```
systemctl stop radarr lidarr
rm -f /var/log/audit/audit.log.*
> /var/log/audit/audit.log
setenforce 0
```
Then you can start, let it run for a while and then create a custom policy:
```
systemctl start radarr lidarr
[wait some time....]
audit2allow -a -M dotnet
semodule -i dotnet.pp
```
Then you can stop and restart it in SELinux mode:
```
systemctl stop radarr lidarr
setenforce 1
systemctl start radarr lidarr
```
They should keep working.

Two possibilites here:

1. Get mad: https://gitlab.com/mediasrv-selinux, as every single piece of software must be in the policies and every possible combination must be considered (ex. speaking to the sabnzbd port, speaking to the transmission port, etc.).
2. Move to containers: https://medium.com/@Pooch/containerized-media-server-setup-with-podman-3727727c8c5f

If you look at the selinux custom policies they are so big that I'm a bit scared about them...

**Comment by scaronni** [comment]
@tim427 can you check the latest updates?
```
# rpm -qa radarr*
radarr-3.1.0.4735-1.el8.x86_64
radarr-selinux-0.1-2.el8.noarch
```
This should be enough to bring up the service with SELinux enabled. If you installed the custom module above (`dotnet`) you should remove it first:
```
systemctl stop radarr
semodule -r dotnet
yum -y update radarr*
setenforce 1
> /var/log/audit.log
systemctl start radarr
```
If you need there is also some more stuff that you can set:
```
# getsebool -a | grep -i radarr
radarr_access_all_ro --> off
radarr_access_all_rw --> off
radarr_access_home_dirs_rw --> off
radarr_anon_write --> off
radarr_list_all_dirs --> off
radarr_send_email --> off
radarr_sys_cert_ro --> off
```

Please let me know, as I need feedback to get these things right. Thanks.

I'll be working on finishing the policies and creating the lidarr one.

**Comment by scaronni** [comment]
@tim427 any feedback?

**Comment by tim427** [comment]
> @tim427 any feedback?

Sorry, had a busy weekend!



> @tim427 can you check the latest updates?
> 
> ```
> # rpm -qa radarr*
> radarr-3.1.0.4735-1.el8.x86_64
> radarr-selinux-0.1-2.el8.noarch
> ```
> 
> This should be enough to bring up the service with SELinux enabled. If you installed the custom module above (`dotnet`) you should remove it first:
> 
> ```
> systemctl stop radarr
> semodule -r dotnet
> yum -y update radarr*
> setenforce 1
> > /var/log/audit.log
> systemctl start radarr
> ```
> 
> If you need there is also some more stuff that you can set:
> 
> ```
> # getsebool -a | grep -i radarr
> radarr_access_all_ro --> off
> radarr_access_all_rw --> off
> radarr_access_home_dirs_rw --> off
> radarr_anon_write --> off
> radarr_list_all_dirs --> off
> radarr_send_email --> off
> radarr_sys_cert_ro --> off
> ```
> 
> Please let me know, as I need feedback to get these things right. Thanks.
> 
> I'll be working on finishing the policies and creating the lidarr one.

After intstalling the latest `radarr` and `radarr-selinux` and re-enable SElinux, It fails on starting with the following message in the `journalctl`;

```
-- Unit radarr.service has finished shutting down.
Mar 15 10:48:26 downloadmachine systemd[1]: Started Automated manager and downloader for Movies.
-- Subject: Unit radarr.service has finished start-up
-- Defined-By: systemd
-- Support: https://access.redhat.com/support
--
-- Unit radarr.service has finished starting up.
--
-- The start-up result is done.
Mar 15 10:48:27 downloadmachine Radarr[242695]: [Info] Bootstrap: Starting Radarr - /usr/lib64/radarr/Radarr - Version 3.1.0.4735
Mar 15 10:48:28 downloadmachine Radarr[242695]: [Info] Router: Application mode: Interactive
Mar 15 10:48:28 downloadmachine Radarr[242695]: [Info] MigrationController: *** Migrating data source=/var/lib/radarr/.config/Radarr/radarr.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
Mar 15 10:48:29 downloadmachine Radarr[242695]: [Info] MigrationController: *** Migrating data source=/var/lib/radarr/.config/Radarr/logs.db;cache size=-20000;datetimekind=Utc;journal mode=Wal;pooling=True;version=3 ***
Mar 15 10:48:29 downloadmachine Radarr[242695]: SQLite notice (283): recovered 16 frames from WAL file /var/lib/radarr/.config/Radarr/logs.db-wal
Mar 15 10:48:29 downloadmachine Radarr[242695]: [Info] WebHostController: Listening on the following URLs:
Mar 15 10:48:29 downloadmachine Radarr[242695]: [Info] WebHostController:   http://*:7878
Mar 15 10:48:29 downloadmachine Radarr[242695]: [Info] RadarrBootstrapper: Starting Web Server
Mar 15 10:48:31 downloadmachine Radarr[242695]: [Fatal] Microsoft.AspNetCore.Server.Kestrel: Unable to start Kestrel.
Mar 15 10:48:31 downloadmachine Radarr[242695]: [v3.1.0.4735] System.Net.Sockets.SocketException (13): Permission denied
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.<Bind>g__BindSocket|13_0(<>c__DisplayClass13_0& )
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass29_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Mar 15 10:48:31 downloadmachine Radarr[242695]: --- End of stack trace from previous location ---
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable`1 listenOptions, AddressBindContext context)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Mar 15 10:48:31 downloadmachine Radarr[242695]:    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Mar 15 10:48:31 downloadmachine Radarr[242695]: [Fatal] ConsoleApp: Permission denied This can happen if another instance of Radarr is already running another application is using the same port (default: 7878) or the user has insufficient permissions
Mar 15 10:48:31 downloadmachine Radarr[242695]: Press enter to exit...
Mar 15 10:48:32 downloadmachine systemd[1]: radarr.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 15 10:48:32 downloadmachine systemd[1]: radarr.service: Failed with result 'exit-code'.
```

The process has difficulties to create a socket. I'll try to investigate this further later on!

**Comment by scaronni** [comment]
Thanks for feedback. That's strange, as it should be fine for that part.

Do you see this on your system?
```
# semanage port -l | grep radarr
radarr_port_t                  tcp      7878
```
Also, please restart with clean audit log and paste the result of `audit2allow -a` here:
```
systemctl stop radarr
setenforce 0
> /var/log/audit.log
systemctl start radarr
audit2allow -a
```
Also prior to starting please confirm the context of the files:
```
# ls -1dZ /var/lib/radarr /usr/lib64/radarr/Radarr /usr/lib64/radarr/Radarr.Update/Radarr.Update
   system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr
   system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr.Update/Radarr.Update
system_u:object_r:radarr_var_lib_t:s0 /var/lib/radarr
# ss -plutnZ | grep 7878
tcp   LISTEN 0      512                *:7878             *:*    users (("Radarr",pid=812785,proc_ctx=system_u:system_r:radarr_t:s0,fd=196)) 
```

**Comment by tim427** [comment]
> Thanks for feedback. That's strange, as it should be fine for that part.

No problem ;) Thanks for your patience (sorry for the late reply)
> 
> Do you see this on your system?
> 
> ```
> # semanage port -l | grep radarr
> radarr_port_t                  tcp      7878
> ```

```
# semanage port -l | grep radarr
```
(no output)

> 
> Also, please restart with clean audit log and paste the result of `audit2allow -a` here:
> 
> ```
> systemctl stop radarr
> setenforce 0
> > /var/log/audit.log
> systemctl start radarr
> audit2allow -a
> ```

Stopped, disabled SE enforcment, cleared the audit.log and started again. The output of audit2allow;
```
# audit2allow -a|grep radarr
#============= radarr_t ==============
allow radarr_t bin_t:file map;
#     radarr_access_all_ro, radarr_access_all_rw
allow radarr_t initrc_exec_t:file getattr;
#!!!! This avc can be allowed using the boolean 'radarr_access_all_rw'
allow radarr_t tmp_t:file { map setattr };
#!!!! This avc can be allowed using the boolean 'radarr_access_all_rw'
allow radarr_t tmp_t:sock_file unlink;
allow radarr_t unreserved_port_t:tcp_socket { name_bind name_connect };
#     radarr_access_all_rw, radarr_access_home_dirs_rw
allow radarr_t user_home_t:dir { add_name create remove_name rmdir write };
#     radarr_access_all_ro, radarr_access_all_rw, radarr_access_home_dirs_rw
allow radarr_t user_home_t:file { lock open read rename unlink };
```

> 
> Also prior to starting please confirm the context of the files:
> 
> ```
> # ls -1dZ /var/lib/radarr /usr/lib64/radarr/Radarr /usr/lib64/radarr/Radarr.Update/Radarr.Update
>    system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr
>    system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr.Update/Radarr.Update
> system_u:object_r:radarr_var_lib_t:s0 /var/lib/radarr
> # ss -plutnZ | grep 7878
> tcp   LISTEN 0      512                *:7878             *:*    users (("Radarr",pid=812785,proc_ctx=system_u:system_r:radarr_t:s0,fd=196)) 
> ```

```
# ls -1dZ /var/lib/radarr /usr/lib64/radarr/Radarr /usr/lib64/radarr/Radarr.Update/Radarr.Update
   system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr
   system_u:object_r:radarr_exec_t:s0 /usr/lib64/radarr/Radarr.Update/Radarr.Update
system_u:object_r:radarr_var_lib_t:s0 /var/lib/radarr
# ss -plutnZ | grep 7878
tcp   LISTEN 0      128                *:7878             *:*    users:(("Radarr",pid=1522962,proc_ctx=system_u:system_r:radarr_t:s0,fd=149))
```

**Comment by scaronni** [comment]
> ```
> # semanage port -l | grep radarr
> ```
> 
> (no output)

Ok, this is not correct, you might want to remove and reinstall the package or the linux policy. I will create an update later today, so maybe it will be fixed by just attempting a reinstall in the update.

> Stopped, disabled SE enforcment, cleared the audit.log and started again. The output of audit2allow;
> 
> ```
> # audit2allow -a|grep radarr
> #============= radarr_t ==============
> allow radarr_t bin_t:file map;
> #     radarr_access_all_ro, radarr_access_all_rw
> allow radarr_t initrc_exec_t:file getattr;
> #!!!! This avc can be allowed using the boolean 'radarr_access_all_rw'
> allow radarr_t tmp_t:file { map setattr };
> #!!!! This avc can be allowed using the boolean 'radarr_access_all_rw'
> allow radarr_t tmp_t:sock_file unlink;
> allow radarr_t unreserved_port_t:tcp_socket { name_bind name_connect };
> #     radarr_access_all_rw, radarr_access_home_dirs_rw
> allow radarr_t user_home_t:dir { add_name create remove_name rmdir write };
> #     radarr_access_all_ro, radarr_access_all_rw, radarr_access_home_dirs_rw
> allow radarr_t user_home_t:file { lock open read rename unlink };
> ```

This seems related to where you have your media library. With SELinux enabled you need to set the `plex_content_rw_t` to the folder where you store content.

**Comment by scaronni** [comment]
@tim427 any news? the policy is working fine for me, also the Lidarr one which is basically the same. If you don't see the port, please force remove the `radarr-selinux` package and its policy and reinstall it:

```
systemctl stop radarr
rpm -e --nodeps radarr-selinux
semodule -n -s  targeted -r radarr
yum -y install radarr-selinux
semanage port -l | grep radarr
systemctl start radarr
```

Also, if you don't want to get mad with labeling everything you can just do `setsebool -P radarr_access_all_rw=on` and this should be enough to get you going to the previous state (i.e. unconfined service where permissions are enforced by actual permissions on files).

**Comment by tim427** [comment]
@scaronni first off, I really admire your persistent troubleshooting ;)

I've removed all the `{rad,son,lid}arr` and installed both `{ra,li}darr-selinux` packages, resulting in the following; 🥳

```
[root@downloadmachine ~]# semanage port -l | grep arr
lidarr_port_t                  tcp      8686
radarr_port_t                  tcp      7878
```

Afterwards, both `{son,rad}arr` are installed correctly together with `setenforce 1`!

But now the following problem arises;

```
[root@downloadmachine ~]# dnf install -y lidar
Dependencies resolved.
=====================================================================================================
 Package           Architecture      Version                        Repository                  Size
=====================================================================================================
Installing:
 lidarr            x86_64            0.8.1.2135-2.el8               epel-multimedia             66 M

Transaction Summary
=====================================================================================================
Install  1 Package

Total size: 66 M
Installed size: 206 M
Downloading Packages:
[SKIPPED] lidarr-0.8.1.2135-2.el8.x86_64.rpm: Already downloaded
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction test error:
  file /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc from install of lidarr-0.8.1.2135-2.el8.x86_64 conflicts with file from package radarr-3.1.0.4893-1.el8.x86_64
  ```

I'm able to "swap" the problem with `radarr` -> Remove `radarr` and correctly install `lidarr` and vice versa :)


```
[root@downloadmachine ~]# file /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc
/usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc: symbolic link to ../../../../usr/lib64/lidarr/libMonoPosixHelper.so
```

After some research; It looks like, these links could be safely disable by adding `%define _build_id_links none` to the spec-file.

**Comment by scaronni** [comment]
> Error: Transaction test error:
>   file /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc from install of lidarr-0.8.1.2135-2.el8.x86_64 conflicts with file from package radarr-3.1.0.4893-1.el8.x86_64
>
> [root@downloadmachine ~]# file /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc
> /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc: symbolic link to ../../../../usr/lib64/lidarr/libMonoPosixHelper.so

 This is weird, it does not throw an error on Fedora 33, the package installs fine:
```
[root@hooloovoo ~]# rpm -qf /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc
lidarr-0.8.1.2135-2.fc33.x86_64
radarr-3.1.0.4893-1.fc33.x86_64
[root@hooloovoo ~]# file /usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc
/usr/lib/.build-id/77/e440bfc6655e56840d6a283f1f567ea8309acc: symbolic link to ../../../../usr/lib64/radarr/libMonoPosixHelper.so
```
And Radarr is built with .NET 5.0 while lidarr with .NET 3.1, I'm surprised the `libMonoPosixHelper.so` library is even the same.

> After some research; It looks like, these links could be safely disable by adding `%define _build_id_links none` to the spec-file.

Thanks, looking into it.

**Comment by scaronni** [comment]
So the build id links are basically useless if the debug packages are not generated (which is not happening with .NET executables) so I'm actually surprised that those are still generated. I've disabled them, thanks.

New build coming in a couple hours.
