### ISSUE TITLE
Not Building?

### ISSUE THREAD

**Issue by dobbleg1000** [negativo17/radarr#2]
I can see master and the branches are updated but I don see a newer version of radarr since september on the repo.

**Comment by scaronni** [comment]
There has been no updates in recent months, just recently versions 4.x came out.

I have issues building on `aarch64`, as `yarn` goes into network time outs and issues on `epel-next-8`, `epel-next-9` and `epel-9` where downloading nuget packages fails miserably without a proper explanation. I was hoping to fix these issue before posting another update, but for the moment I've pushed it for `el7`, `el8`, `fc34` and `fc35`.

You should get the updated packages in a few minutes.
