### ISSUE TITLE
Unable to update "radarr-4.0.4.5922-2"

### ISSUE THREAD

**Issue by tim427** [negativo17/radarr#3]
```
[root@machine ~]# dnf update
Error:
 Problem: cannot install the best update candidate for package radarr-4.0.4.5922-1.el8.x86_64
  - nothing provides libc.musl-x86_64.so.1()(64bit) needed by radarr-4.0.4.5922-2.el8.x86_64
  - nothing provides libintl.so.8()(64bit) needed by radarr-4.0.4.5922-2.el8.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
No results for both:
- https://pkgs.org/search/?q=libintl.so
- https://pkgs.org/search/?q=libc.musl

Anyone with tips/tricks?

```
[root@machine ~]# cat /etc/centos-release
CentOS Stream release 8
```

**Comment by scaronni** [comment]
The test coverage stuff is included by mistake in the package since they changed the build a little. Working on removing all of that.

**Comment by tim427** [comment]
[c165685](https://github.com/negativo17/radarr/commit/c165685a45ad9a2a071359a872ea75871c25f99b) Fixed the issue!
