### ISSUE TITLE
Broken Dependency on radarr-selinx in Fedora 37 repo

### ISSUE THREAD

**Issue by Andrew-McGee** [negativo17/radarr#5]
Hi Simone,

Thanks for all your efforts packaging this. I tried installing from your repo and got a broken dependency:

```
package radarr-4.3.2.6857-1.fc37.x86_64 requires (radarr-selinux if selinux-policy), but none of the providers can be installed
```
I also noticed the same thing happen with lidarr.

**Comment by scaronni** [comment]
Sorry, forgot to tag them for Fedora 37. Will be online shortly.
